// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ49W1Im4_8ZzS0V54jhSGjN3xGNtpF0Y',
    appId: '1:334572753544:web:d23ddbd8b4a2906109053d',
    messagingSenderId: '334572753544',
    projectId: 'phoneauthsignin',
    authDomain: 'phoneauthsignin.firebaseapp.com',
    storageBucket: 'phoneauthsignin.appspot.com',
    measurementId: 'G-G6LDSQ94R9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCKKeorwANAvEOni3CLgANP1XQKioqIto',
    appId: '1:334572753544:android:5e9ae9be4d7215ce09053d',
    messagingSenderId: '334572753544',
    projectId: 'phoneauthsignin',
    storageBucket: 'phoneauthsignin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-KHyx8LDCTAChWLxtM03HTuezc9CFaso',
    appId: '1:334572753544:ios:5558765074cd54ae09053d',
    messagingSenderId: '334572753544',
    projectId: 'phoneauthsignin',
    storageBucket: 'phoneauthsignin.appspot.com',
    iosBundleId: 'com.example.phoneZadanie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-KHyx8LDCTAChWLxtM03HTuezc9CFaso',
    appId: '1:334572753544:ios:4f9737fac1feebad09053d',
    messagingSenderId: '334572753544',
    projectId: 'phoneauthsignin',
    storageBucket: 'phoneauthsignin.appspot.com',
    iosBundleId: 'com.example.phoneZadanie.RunnerTests',
  );
}
